from .signin_page import SignInPage
from .location_page import LocationPage
from .home_page import Homepage
from .category_page import Categorypage
from .cartsummary_page import CartSummaryPage
from .deliverysummary_page import DeliverySummaryPage
from .payment_page import PaymentPage
from .chat_page import Chatpage
from .myaccount_page import MyAccountepage
from .search_page import SearchPage
from .signup_page import SignupPage
from .humbergermenu import Humbergermenu
from .verify_magento_order import Verifymagento
from .forgetpassword_page import ForegetpasswordPage
from .storecredit_page import Storecredit
from .order_page import OrderPage
from .magento_inventory import Inventory
from .address_page import AddressPage